[[headers]]
for = "/*" # Apply these headers to all paths
  [headers.values]
  Content-Security-Policy = "default-src 'self'; \
                             script-src 'self' 'unsafe-inline' 'unsafe-eval'; \
                             style-src 'self' 'unsafe-inline'; \
                             img-src 'self' data:; \
                             font-src 'self'; \
                             connect-src 'self' https://uniflow.ap-southeast-2.elasticbeanstalk.com wss://uniflow.ap-southeast-2.elasticbeanstalk.com;"