services:
  # Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=5001
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./client/src:/app/src
      - ./client/vite.config.js:/app/vite.config.js
      - ./client/index.html:/app/index.html
      - /app/node_modules
    env_file:
      - ./client/.env
    environment:
      - VITE_API_URL=http://server:5001
    depends_on:
      - server
    restart: unless-stopped