/**
 * tasksSlice.js
 * Manages all task-related API queries and mutations with RTK Query.
 */
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

const TASK_API_URL = import.meta.env.VITE_API_URL;

export const taskApiSlice = createApi({
  reducerPath: 'taskApi', // Unique key for the tasks slice
  baseQuery: fetchBaseQuery({
    baseUrl: TASK_API_URL,
    credentials: 'include',
  }),
  tagTypes: ['Task'],
  endpoints: (builder) => ({
    // Fetch tasks by project ID
    getTasksByProject: builder.query({
      query: (projectId) => `/tasks/${projectId}`,                        // change task route to fetch project tasks
      providesTags: (result, error, projectId) => [{ type: 'Task', id: projectId }],
    }),

    // Create a new task
    addTask: builder.mutation({
      query: (newTask) => ({
        url: '/tasks',
        method: 'POST',
        body: newTask,
      }),
      invalidatesTags: [{ type: 'Task', id: 'LIST' }],
    }),

    // Update an existing task
    updateTask: builder.mutation({
      query: (updatedTask) => ({
        url: `/tasks/${updatedTask._id}`,
        method: 'PUT',
        body: updatedTask,
      }),
      invalidatesTags: (result, error, updatedTask) => [
        { type: 'Task', id: updatedTask._id },
      ],
    }),

    // Delete a task
    deleteTask: builder.mutation({
      query: (id) => ({
        url: `/tasks/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: (result, error, id) => [{ type: 'Task', id }],
    }),

    /** USER-TASK RELATED QUERIES */
    // Task assignment endpoints
    addUserToTask: builder.mutation({
      query: ({ taskId, userId }) => ({
        url: `/tasks/${taskId}/assign`,
        method: 'POST',
        body: { userId }
      }),
      invalidatesTags: (result, error, { taskId }) => [
        { type: 'Task', id: taskId }
      ]
    }),
    
    removeUserFromTask: builder.mutation({
      query: ({ taskId, userId }) => ({
        url: `/tasks/${taskId}/assign/${userId}`,
        method: 'DELETE'
      }),
      invalidatesTags: (result, error, { taskId }) => [
        { type: 'Task', id: taskId }
      ]
    }),
    
    // Get users assigned to a task
    getTaskUsers: builder.query({
      query: (taskId) => `/tasks/${taskId}/assignees`,
      providesTags: (result, error, taskId) => [
        { type: 'Task', id: taskId }
      ]
    }),
  }),
});

// Export hooks generated by RTK Query for usage in functional components
export const {
  useGetTasksByProjectQuery,
  useAddTaskMutation,
  useUpdateTaskMutation,
  useDeleteTaskMutation,
  useAddUserToTaskMutation,
  useRemoveUserFromTaskMutation,
  useGetTaskUsersQuery,
} = taskApiSlice;

export default taskApiSlice;