name: Project Management Automation

on:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/add-to-project@v0.5.0
      with:
        project-url: https://github.com/users/tda-8818/projects/4 
        github-token: ${{ secrets.GITHUB_TOKEN }}